<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta http-equiv="Content-Type" charset="utf-8" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Font awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>Fog Carport Designe Centre</title>
    <style>
        body {
            position: relative;
            text-align: center;
            font-family: "Arial Black";
            color: #333333;
        }
        .centered {
            position: absolute;
            top: 500px;
            left: 50%;
            transform: translate(-50%, -50%);
        }
        .container1 {
          position:relative;
                top: 10px;
                left: 10px;
                z-index: 1;
        }
        .topimage {
          position:absolute;
                top: 10px;
                left: 25px;
                z-index: 2;
        }

    </style>

</head>
<body>

